### ISSUE TITLE
Error running index.js

### ISSUE THREAD

**Issue by jimmyaldape** [jimmyaldape/laravel-docker-base#7]
## Reproduction Steps:
- clone repository
- run ``npm install``
- run ``node .``

## Error Message
```fs.js:150
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received { recursive: true }
    at makeCallback (fs.js:150:11)
    at Object.rmdir (fs.js:682:14)
    at Object.<anonymous> (/Users/jimmy/dev/temp/xyd/index.js:21:4)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11

**Comment by jimmyaldape** [comment]
this may be caused because node version 12.10.0 is required in order to use ``fs.rmdir`` function and my version is 12.8.x
